/**
 * `/api/v1/webhooks` — PF-302 (Linear TRO-431, PLUGFORGE.MD §2.2/§4).
 *
 * `POST /` (create + mint `whsec_...` once), `GET /` (cursor-paginated,
 * keyset — mirrors `resources/documents.ts`'s list route), `GET /:id`,
 * `DELETE /:id` (deactivate), `POST /:id/rotate` (mint a new secret, once).
 * Every route is gated by `requireScope('webhooks:manage')` — PF-107
 * (`platform/scopes/registry.ts`) already registers that scope; nothing
 * here adds it.
 *
 * **Ownership model.** A `webhook_subscriptions` row belongs to an
 * `app_id` (§2.2's table — not to a workspace directly, and not to the
 * calling user). Every route resolves the caller's workspace the same way
 * `resources/documents.ts` does (`resolvePrincipalWorkspaceId`), then scopes
 * every query through a join back to `oauth_apps.workspace_id` — a
 * subscription is only visible/mutable to a caller whose credential
 * resolves to the SAME workspace that owns the `app_id` it was created
 * under. `POST /` additionally validates that the `app_id` in the request
 * body actually belongs to the caller's workspace before creating anything
 * — a `validation_failed` (not `not_found`) response, because `app_id` is a
 * body field being validated, not a path segment being looked up (the
 * distinction `resources/documents.ts`'s `GET /:id` draws the other way for
 * its own path-segment `id`).
 *
 * **Secret handling (the ticket's own AC, PLUGFORGE.MD §2.2 note).**
 * `POST /` and `POST /:id/rotate` are the ONLY two responses that ever
 * contain a plaintext secret — generated by `webhooks/secrets.ts`,
 * encrypted at rest by `webhooks/secretEncryption.ts` (AES-256-GCM), and
 * returned in the response body exactly once. `WebhookSubscriptionRow` (this
 * file) and every serializer below never select or expose
 * `signing_secret_ciphertext` — there is no "reveal" endpoint, and no field
 * on any GET/list/DELETE response could accidentally carry it, because the
 * row type callers actually touch never has it as a member. See
 * `__tests__/webhooks.test.ts`'s "secret non-recoverable" case for the proof.
 *
 * **DELETE semantics.** Deactivates (`active = false`) rather than a hard
 * `DELETE FROM` — the row is kept so a future `webhook_deliveries` row
 * (migration 045 in PLUGFORGE.MD's table, not yet built by this ticket) can
 * still FK-reference `subscription_id` for its delivery log/DLQ/replay
 * history, matching this codebase's existing revocation-over-deletion
 * precedent (`oauth_apps.revoked_at`, `appRegistration.ts`). HTTP-level this
 * is still a real DELETE: idempotent, `204 No Content`, no distinct
 * "already deleted" error — a second call against an already-inactive
 * subscription is not a client error (HTTP DELETE's own idempotency
 * contract), unlike `rotateOAuthAppSecret`'s `already_revoked` (that
 * function tracks first-vs-subsequent because *revocation* has an audit
 * meaning subsequent callers should be told about; a second deactivate here
 * does not).
 *
 * **Rotation — no grace period (PF-102 precedent, per this ticket's own
 * brief).** `rotateOAuthAppSecret` (`platform/oauth/appRegistration.ts`)
 * documents its own no-grace-period choice: a single-column UPDATE
 * overwrites the stored value in place, so there is nowhere to keep an old
 * value even if a future change wanted to. `POST /:id/rotate` below follows
 * the identical shape for `signing_secret_ciphertext` — the old secret's
 * ciphertext is gone the instant this UPDATE commits, so any HMAC computed
 * against it (a future PF-304 delivery, or `__tests__/webhooks.test.ts`'s
 * "rotation invalidates" case) can never validate again.
 */

import { Router } from 'express';
import type { Request, Router as RouterType } from 'express';
import { z } from 'zod';
import { pool } from '../../../../db/client.js';
import { bearerAuth } from '../../../oauth/bearerAuth.js';
import { requireScope } from '../../../scopes/requireScope.js';
import { asyncHandler } from '../errorMiddleware.js';
import {
  notFoundError,
  serverError,
  validationFailedError,
} from '../errors.js';
import { encodeCursor, decodeCursor, type KeysetCursor } from '../pagination.js';
import { resolvePrincipalWorkspaceId } from './workspaceContext.js';
import { EVENT_TYPES } from '../../../webhooks/events.js';
import { generateWebhookSecret } from '../../../webhooks/secrets.js';
import { encryptSecret } from '../../../webhooks/secretEncryption.js';

export const webhooksRouter: RouterType = Router();

/** Same defensive fallback pattern as `resources/documents.ts`'s own
 * `requestIdOf` — every request reaching a `webhooksRouter` handler already
 * ran `requestIdMiddleware` (mounted first on `v1Router`), so the fallback
 * is not expected to be exercised in practice. */
function requestIdOf(req: Request): string {
  return req.requestId ?? 'missing-request-id';
}

/** `platform/webhooks/events.ts`'s `EVENT_TYPES`, verbatim — the single
 * source of truth PF-300 already established. See migration 047's header
 * for why this validation is deliberately application-level (this zod
 * schema), not a DB CHECK constraint duplicating the same list. */
export const WebhookEventTypeSchema = z.enum(EVENT_TYPES);

/** `POST /api/v1/webhooks` request body. `app_id` must reference an
 * `oauth_apps` row in the caller's own workspace (checked in the handler,
 * not expressible in a zod schema). */
export const CreateWebhookSubscriptionRequestSchema = z.object({
  app_id: z.string().uuid('app_id must be a UUID.'),
  event_type: WebhookEventTypeSchema,
  target_url: z.string().url('target_url must be a valid URL.'),
});

/** `GET /api/v1/webhooks` query params — same cursor-pagination shape as
 * `resources/documents.ts`'s `ListDocumentsQuerySchema` (PF-203). */
export const ListWebhookSubscriptionsQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).optional().default(20),
  cursor: z.string().min(1).optional(),
});

/** Row shape for `webhook_subscriptions` (migration 047) as read by every
 * route in this file — deliberately never includes
 * `signing_secret_ciphertext` (see file header). */
interface WebhookSubscriptionRow {
  id: string;
  app_id: string;
  event_type: string;
  target_url: string;
  active: boolean;
  created_at: Date;
}

const SUBSCRIPTION_COLUMNS = 'ws.id, ws.app_id, ws.event_type, ws.target_url, ws.active, ws.created_at';

function serializeSubscription(row: WebhookSubscriptionRow) {
  return {
    id: row.id,
    app_id: row.app_id,
    event_type: row.event_type,
    target_url: row.target_url,
    active: row.active,
    created_at: row.created_at.toISOString(),
  };
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Resolves `req.principal`'s workspace, or throws the right `ApiError` when
 * that is not possible — the exact `documents.ts` pattern, factored out
 * here because every one of this file's five routes repeats it. Returns
 * `null` only for the "no workspace, but not an error" list-route case
 * (mirroring `documents.ts`'s `GET /` behavior); callers that must have a
 * workspace pass `required: true` and get a thrown `ApiError` instead. */
async function resolveWorkspaceOrThrow(
  req: Request,
  requestId: string
): Promise<string> {
  const principal = req.principal;
  if (!principal) {
    // Unreachable in practice — bearerAuth never calls next() without
    // setting req.principal — but TypeScript can't see that guarantee
    // statically (req.principal is typed optional).
    throw serverError(requestId);
  }
  const workspaceId = await resolvePrincipalWorkspaceId(principal);
  if (!workspaceId) {
    throw notFoundError(requestId, 'No workspace is associated with this credential.');
  }
  return workspaceId;
}

// ─── POST /api/v1/webhooks ───────────────────────────────────────────────

webhooksRouter.post(
  '/',
  bearerAuth,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);

    const parseResult = CreateWebhookSubscriptionRequestSchema.safeParse(req.body);
    if (!parseResult.success) {
      throw validationFailedError(requestId, 'The request could not be validated.', {
        fieldErrors: parseResult.error.flatten().fieldErrors,
      });
    }

    const workspaceId = await resolveWorkspaceOrThrow(req, requestId);

    const appLookup = await pool.query<{ id: string }>(
      `SELECT id FROM oauth_apps WHERE id = $1 AND workspace_id = $2`,
      [parseResult.data.app_id, workspaceId]
    );
    if (!appLookup.rows[0]) {
      throw validationFailedError(requestId, 'app_id does not reference an app in your workspace.', {
        fieldErrors: { app_id: ['no such app in your workspace'] },
      });
    }

    const plaintextSecret = generateWebhookSecret();
    const ciphertext = encryptSecret(plaintextSecret);

    const result = await pool.query<WebhookSubscriptionRow>(
      `INSERT INTO webhook_subscriptions (app_id, event_type, target_url, signing_secret_ciphertext, active)
       VALUES ($1, $2, $3, $4, true)
       RETURNING id, app_id, event_type, target_url, active, created_at`,
      [parseResult.data.app_id, parseResult.data.event_type, parseResult.data.target_url, ciphertext]
    );
    const row = result.rows[0];
    if (!row) {
      throw serverError(requestId);
    }

    // The only response, ever, that carries `secret`. Not stored anywhere
    // beyond this local variable and this one JSON body — AC: "secret
    // non-recoverable via API after creation."
    res.status(201).json({
      ...serializeSubscription(row),
      secret: plaintextSecret,
      warning: 'Save this secret now. It will not be shown again.',
    });
  })
);

// ─── GET /api/v1/webhooks ────────────────────────────────────────────────

webhooksRouter.get(
  '/',
  bearerAuth,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);

    const parseResult = ListWebhookSubscriptionsQuerySchema.safeParse(req.query);
    if (!parseResult.success) {
      throw validationFailedError(requestId, 'Invalid query parameters.', {
        fieldErrors: parseResult.error.flatten().fieldErrors,
      });
    }
    const { limit, cursor } = parseResult.data;

    let decodedCursor: KeysetCursor | null = null;
    if (cursor !== undefined) {
      decodedCursor = decodeCursor(cursor);
      if (!decodedCursor) {
        throw validationFailedError(requestId, 'Invalid cursor.', {
          fieldErrors: { cursor: ['cursor is not a valid opaque cursor'] },
        });
      }
    }

    const principal = req.principal;
    if (!principal) {
      throw serverError(requestId);
    }
    const workspaceId = await resolvePrincipalWorkspaceId(principal);
    if (!workspaceId) {
      // Same "fail closed to an empty page" convention as documents.ts.
      res.status(200).json({ data: [], next_cursor: null });
      return;
    }

    const values: unknown[] = [workspaceId];
    const whereClauses = ['a.workspace_id = $1'];

    if (decodedCursor) {
      values.push(decodedCursor.created_at, decodedCursor.id);
      whereClauses.push(`(ws.created_at, ws.id) < ($${values.length - 1}, $${values.length})`);
    }

    values.push(limit + 1);
    const limitParamIndex = values.length;

    const result = await pool.query<WebhookSubscriptionRow>(
      `SELECT ${SUBSCRIPTION_COLUMNS}
       FROM webhook_subscriptions ws
       JOIN oauth_apps a ON a.id = ws.app_id
       WHERE ${whereClauses.join(' AND ')}
       ORDER BY ws.created_at DESC, ws.id DESC
       LIMIT $${limitParamIndex}`,
      values
    );

    const rows = result.rows;
    const hasMore = rows.length > limit;
    const page = hasMore ? rows.slice(0, limit) : rows;
    const lastRow = page[page.length - 1];
    const nextCursor =
      hasMore && lastRow
        ? encodeCursor({ id: lastRow.id, created_at: lastRow.created_at.toISOString() })
        : null;

    res.status(200).json({
      data: page.map(serializeSubscription),
      next_cursor: nextCursor,
    });
  })
);

// ─── GET /api/v1/webhooks/:id ────────────────────────────────────────────

webhooksRouter.get(
  '/:id',
  bearerAuth,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);
    const id = String(req.params.id);

    if (!UUID_RE.test(id)) {
      throw notFoundError(requestId);
    }

    const principal = req.principal;
    if (!principal) {
      throw serverError(requestId);
    }
    const workspaceId = await resolvePrincipalWorkspaceId(principal);
    if (!workspaceId) {
      throw notFoundError(requestId);
    }

    const result = await pool.query<WebhookSubscriptionRow>(
      `SELECT ${SUBSCRIPTION_COLUMNS}
       FROM webhook_subscriptions ws
       JOIN oauth_apps a ON a.id = ws.app_id
       WHERE ws.id = $1 AND a.workspace_id = $2`,
      [id, workspaceId]
    );

    const row = result.rows[0];
    if (!row) {
      throw notFoundError(requestId);
    }

    res.status(200).json(serializeSubscription(row));
  })
);

// ─── DELETE /api/v1/webhooks/:id ─────────────────────────────────────────

webhooksRouter.delete(
  '/:id',
  bearerAuth,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);
    const id = String(req.params.id);

    if (!UUID_RE.test(id)) {
      throw notFoundError(requestId);
    }

    const workspaceId = await resolveWorkspaceOrThrow(req, requestId);

    // Deactivates rather than deletes — see file header. No `active = true`
    // filter in the WHERE clause: a repeat call against an already-inactive
    // subscription still matches and still returns 204 (idempotent DELETE),
    // it just has nothing left to change.
    const result = await pool.query<{ id: string }>(
      `UPDATE webhook_subscriptions ws
       SET active = false
       FROM oauth_apps a
       WHERE ws.id = $1 AND ws.app_id = a.id AND a.workspace_id = $2
       RETURNING ws.id`,
      [id, workspaceId]
    );

    if (!result.rows[0]) {
      throw notFoundError(requestId);
    }

    res.status(204).send();
  })
);

// ─── POST /api/v1/webhooks/:id/rotate ────────────────────────────────────

webhooksRouter.post(
  '/:id/rotate',
  bearerAuth,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);
    const id = String(req.params.id);

    if (!UUID_RE.test(id)) {
      throw notFoundError(requestId);
    }

    const workspaceId = await resolveWorkspaceOrThrow(req, requestId);

    const plaintextSecret = generateWebhookSecret();
    const ciphertext = encryptSecret(plaintextSecret);

    // Single-column UPDATE, no grace period — see file header (PF-102
    // `rotateOAuthAppSecret` precedent). The old ciphertext is gone the
    // instant this commits; nothing keeps it around for a fallback verify.
    const result = await pool.query<WebhookSubscriptionRow>(
      `UPDATE webhook_subscriptions ws
       SET signing_secret_ciphertext = $1
       FROM oauth_apps a
       WHERE ws.id = $2 AND ws.app_id = a.id AND a.workspace_id = $3
       RETURNING ws.id, ws.app_id, ws.event_type, ws.target_url, ws.active, ws.created_at`,
      [ciphertext, id, workspaceId]
    );

    const row = result.rows[0];
    if (!row) {
      throw notFoundError(requestId);
    }

    res.status(200).json({
      ...serializeSubscription(row),
      secret: plaintextSecret,
      warning: 'Save this secret now. It will not be shown again.',
    });
  })
);
