/**
 * `/api/v1/webhooks` — PF-302 (Linear TRO-431, PLUGFORGE.MD §2.2/§4).
 *
 * `POST /` (create + mint `whsec_...` once), `GET /` (cursor-paginated,
 * keyset — mirrors `resources/documents.ts`'s list route), `GET /:id`,
 * `DELETE /:id` (deactivate), `POST /:id/rotate` (mint a new secret, once).
 * Every route is gated by `requireScope('webhooks:manage')` — PF-107
 * (`platform/scopes/registry.ts`) already registers that scope; nothing
 * here adds it.
 *
 * **Ownership model.** A `webhook_subscriptions` row belongs to an
 * `app_id` (§2.2's table — not to a workspace directly, and not to the
 * calling user). Every route resolves the caller's workspace the same way
 * `resources/documents.ts` does (`resolvePrincipalWorkspaceId`), then scopes
 * every query through a join back to `oauth_apps.workspace_id` — a
 * subscription is only visible/mutable to a caller whose credential
 * resolves to the SAME workspace that owns the `app_id` it was created
 * under. `POST /` additionally validates that the `app_id` in the request
 * body actually belongs to the caller's workspace before creating anything
 * — a `validation_failed` (not `not_found`) response, because `app_id` is a
 * body field being validated, not a path segment being looked up (the
 * distinction `resources/documents.ts`'s `GET /:id` draws the other way for
 * its own path-segment `id`).
 *
 * **Secret handling (the ticket's own AC, PLUGFORGE.MD §2.2 note).**
 * `POST /` and `POST /:id/rotate` are the ONLY two responses that ever
 * contain a plaintext secret — generated by `webhooks/secrets.ts`,
 * encrypted at rest by `webhooks/secretEncryption.ts` (AES-256-GCM), and
 * returned in the response body exactly once. `WebhookSubscriptionRow` (this
 * file) and every serializer below never select or expose
 * `signing_secret_ciphertext` — there is no "reveal" endpoint, and no field
 * on any GET/list/DELETE response could accidentally carry it, because the
 * row type callers actually touch never has it as a member. See
 * `__tests__/webhooks.test.ts`'s "secret non-recoverable" case for the proof.
 *
 * **DELETE semantics.** Deactivates (`active = false`) rather than a hard
 * `DELETE FROM` — the row is kept so a future `webhook_deliveries` row
 * (migration 045 in PLUGFORGE.MD's table, not yet built by this ticket) can
 * still FK-reference `subscription_id` for its delivery log/DLQ/replay
 * history, matching this codebase's existing revocation-over-deletion
 * precedent (`oauth_apps.revoked_at`, `appRegistration.ts`). HTTP-level this
 * is still a real DELETE: idempotent, `204 No Content`, no distinct
 * "already deleted" error — a second call against an already-inactive
 * subscription is not a client error (HTTP DELETE's own idempotency
 * contract), unlike `rotateOAuthAppSecret`'s `already_revoked` (that
 * function tracks first-vs-subsequent because *revocation* has an audit
 * meaning subsequent callers should be told about; a second deactivate here
 * does not).
 *
 * **Rotation — no grace period (PF-102 precedent, per this ticket's own
 * brief).** `rotateOAuthAppSecret` (`platform/oauth/appRegistration.ts`)
 * documents its own no-grace-period choice: a single-column UPDATE
 * overwrites the stored value in place, so there is nowhere to keep an old
 * value even if a future change wanted to. `POST /:id/rotate` below follows
 * the identical shape for `signing_secret_ciphertext` — the old secret's
 * ciphertext is gone the instant this UPDATE commits, so any HMAC computed
 * against it (a future PF-304 delivery, or `__tests__/webhooks.test.ts`'s
 * "rotation invalidates" case) can never validate again.
 *
 * **`GET /deliveries` (PF-305, TRO-442) — the delivery log.** Added below
 * `GET /` and deliberately BEFORE `GET /:id` in this file's route
 * registration order: Express matches routes in registration order, and
 * `webhook_deliveries` is a plain sibling path segment (`/webhooks/deliveries`),
 * not a resource nested under a subscription id — if it were registered
 * after `GET /:id`, the literal string `"deliveries"` would match `:id` first
 * and 404 (it fails `UUID_RE`) before this route ever ran. One row per
 * delivery ATTEMPT (migration 048's own row-per-attempt design — a retried
 * delivery leaves multiple rows, one per `attempt_number`, sharing
 * `event_id`), scoped to subscriptions whose `app_id` resolves to the
 * caller's workspace via the same `oauth_apps` join every other route in
 * this file uses. Filterable by `subscription_id` and `status`; cursor-
 * paginated per the same `(created_at, id) DESC` keyset shape as `GET /`.
 * Never selects `payload` (the full event envelope) — `response_excerpt`
 * already caps what a delivery attempt costs to display, and the raw
 * payload belongs to a future replay endpoint (PF-306), not this log view.
 *
 * **`POST /deliveries/:id/replay` (PF-306, TRO-446) — replay from the
 * delivery log.** Re-runs a logged delivery (looked up workspace-scoped, the
 * same join as `GET /deliveries`) through `webhooks/deliverer.ts`'s
 * `attemptNow()`, carrying the ORIGINAL `idempotency_key` — never a freshly
 * generated one; this is the subscriber-dedupe contract PF-801's future e2e
 * test verifies. Works regardless of the original row's status, `dead`
 * (DLQ) included — this route never branches on it. Creates a NEW
 * `webhook_deliveries` row (never mutates the original), linked back via
 * `replayed_from_id` (migration 049) and sharing the original's `event_id`,
 * with `attempt_number` continuing that event's existing attempt series
 * (migration 048's unique index is keyed on `(subscription_id, event_id,
 * attempt_number)`).
 */

import { Router } from 'express';
import type { Request, Router as RouterType } from 'express';
import { z } from 'zod';
import { pool } from '../../../../db/client.js';
import { bearerAuth } from '../../../oauth/bearerAuth.js';
import { requireScope } from '../../../scopes/requireScope.js';
import { rateLimitBuckets } from '../../../ratelimit/middleware.js';
import { asyncHandler } from '../errorMiddleware.js';
import {
  notFoundError,
  serverError,
  validationFailedError,
} from '../errors.js';
import { encodeCursor, decodeCursor, type KeysetCursor } from '../pagination.js';
import { resolvePrincipalWorkspaceId } from './workspaceContext.js';
import { EVENT_TYPES } from '../../../webhooks/events.js';
import { generateWebhookSecret } from '../../../webhooks/secrets.js';
import { encryptSecret } from '../../../webhooks/secretEncryption.js';
import { InMemoryWebhookDeliverer, isKnownEventType } from '../../../webhooks/deliverer.js';

export const webhooksRouter: RouterType = Router();

/** Same defensive fallback pattern as `resources/documents.ts`'s own
 * `requestIdOf` — every request reaching a `webhooksRouter` handler already
 * ran `requestIdMiddleware` (mounted first on `v1Router`), so the fallback
 * is not expected to be exercised in practice. */
function requestIdOf(req: Request): string {
  return req.requestId ?? 'missing-request-id';
}

/** `platform/webhooks/events.ts`'s `EVENT_TYPES`, verbatim — the single
 * source of truth PF-300 already established. See migration 047's header
 * for why this validation is deliberately application-level (this zod
 * schema), not a DB CHECK constraint duplicating the same list. */
export const WebhookEventTypeSchema = z.enum(EVENT_TYPES);

const HTTP_URL_SCHEMES = new Set(['http:', 'https:']);

/**
 * `target_url` must be syntactically valid (`z.string().url()`) AND use an
 * http/https scheme — rejects `javascript:`, `file:`, `ftp:`, etc. at the
 * cheapest possible layer (no DNS lookup, no network call).
 *
 * Deliberately NOT extended to reject loopback/link-local/private-IP hosts
 * here (CodeRabbit review, this PR — taken seriously, not dismissed: this is
 * a real SSRF-adjacent concern, but the fix belongs at a different layer).
 * A hostname's DNS answer can change between "this row is created" and
 * "PF-304 actually dials target_url" (DNS rebinding is exactly this
 * attack), so a host/IP check performed here would be checking a value that
 * is no longer authoritative by delivery time — theater, not protection.
 * The check that actually defends the delivery path has to run at PF-304's
 * connect time, against the IP it is about to open a socket to. Left as an
 * explicit, named gap for PF-304 to close, not silently absent.
 */
function isHttpUrl(value: string): boolean {
  try {
    return HTTP_URL_SCHEMES.has(new URL(value).protocol);
  } catch {
    return false;
  }
}

/** `POST /api/v1/webhooks` request body. `app_id` must reference an
 * `oauth_apps` row in the caller's own workspace (checked in the handler,
 * not expressible in a zod schema). */
export const CreateWebhookSubscriptionRequestSchema = z.object({
  app_id: z.string().uuid('app_id must be a UUID.'),
  event_type: WebhookEventTypeSchema,
  target_url: z
    .string()
    .url('target_url must be a valid URL.')
    .refine(isHttpUrl, { message: 'target_url must use the http or https scheme.' }),
});

/** `GET /api/v1/webhooks` query params — same cursor-pagination shape as
 * `resources/documents.ts`'s `ListDocumentsQuerySchema` (PF-203). */
export const ListWebhookSubscriptionsQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).optional().default(20),
  cursor: z.string().min(1).optional(),
});

/** Row shape for `webhook_subscriptions` (migration 047) as read by every
 * route in this file — deliberately never includes
 * `signing_secret_ciphertext` (see file header). */
interface WebhookSubscriptionRow {
  id: string;
  app_id: string;
  event_type: string;
  target_url: string;
  active: boolean;
  created_at: Date;
}

const SUBSCRIPTION_COLUMNS = 'ws.id, ws.app_id, ws.event_type, ws.target_url, ws.active, ws.created_at';

function serializeSubscription(row: WebhookSubscriptionRow) {
  return {
    id: row.id,
    app_id: row.app_id,
    event_type: row.event_type,
    target_url: row.target_url,
    active: row.active,
    created_at: row.created_at.toISOString(),
  };
}

/** `GET /api/v1/webhooks/deliveries` query params — same cursor-pagination
 * shape as `ListWebhookSubscriptionsQuerySchema` (PF-203), plus the two
 * caller-supplied filters this ticket's AC names. `status` is validated
 * against `deliverer.ts`'s own `WebhookDeliveryStatus` union, kept in sync
 * here by hand (that file's own status literals are not re-exported as a
 * zod schema, matching this codebase's "events as data" precedent for
 * `event_type` — see migration 048's header). */
export const ListWebhookDeliveriesQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).optional().default(20),
  cursor: z.string().min(1).optional(),
  subscription_id: z.string().uuid('subscription_id must be a UUID.').optional(),
  status: z.enum(['pending', 'success', 'failed', 'dead']).optional(),
});

/** Row shape for `webhook_deliveries` (migration 048, plus migration 049's
 * `replayed_from_id`) as read by the delivery-log route — deliberately never
 * selects `payload`, see file header. `replayed_from_id` is non-NULL only for
 * a row created by `POST /deliveries/:id/replay` (PF-306, TRO-446); NULL for
 * every row the normal enqueueEvent()/attempt() pipeline creates (a fresh
 * delivery or one of its own automatic retries). Surfaced on both this row
 * type and the list route below (not just the replay route's own response)
 * so a caller can tell, from the delivery log alone, which rows are replays
 * and which they replayed FROM. */
interface WebhookDeliveryRow {
  id: string;
  subscription_id: string;
  event_id: string;
  event_type: string;
  idempotency_key: string;
  attempt_number: number;
  status: string;
  response_status: number | null;
  response_excerpt: string | null;
  latency_ms: number | null;
  next_attempt_at: Date | null;
  replayed_from_id: string | null;
  created_at: Date;
}

const DELIVERY_COLUMNS =
  'wd.id, wd.subscription_id, wd.event_id, wd.event_type, wd.idempotency_key, wd.attempt_number, wd.status, wd.response_status, wd.response_excerpt, wd.latency_ms, wd.next_attempt_at, wd.replayed_from_id, wd.created_at';

function serializeDelivery(row: WebhookDeliveryRow) {
  return {
    id: row.id,
    subscription_id: row.subscription_id,
    event_id: row.event_id,
    event_type: row.event_type,
    idempotency_key: row.idempotency_key,
    attempt_number: row.attempt_number,
    status: row.status,
    response_status: row.response_status,
    response_excerpt: row.response_excerpt,
    latency_ms: row.latency_ms,
    next_attempt_at: row.next_attempt_at ? row.next_attempt_at.toISOString() : null,
    replayed_from_id: row.replayed_from_id,
    created_at: row.created_at.toISOString(),
  };
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Narrows a `catch` value to "a pg `DatabaseError` with this SQLSTATE code"
 * — same `instanceof Error && 'code' in error` runtime-shape-check pattern
 * `config/ssm.ts`'s `isAbortError` already uses for narrowing an unknown
 * catch value (no `as any`/`as unknown as` cast; `pg` does not export a
 * typed `DatabaseError` this codebase imports elsewhere). Used by `POST /`
 * to turn migration 047's `idx_webhook_subscriptions_unique_active`
 * violation (`23505`) into a `validation_failed` `ApiError` instead of a
 * sanitized `server_error`. */
function isPgErrorWithCode(error: unknown, expectedCode: string): boolean {
  return error instanceof Error && 'code' in error && error.code === expectedCode;
}

/** Resolves `req.principal`'s workspace, or `null` when none resolves (e.g. a
 * personal token for a user who has never joined a workspace, or a dangling
 * `app_id`) — never throws for that case. Every route in this file needs the
 * principal-missing guard (`serverError` — unreachable in practice, since
 * `bearerAuth` never calls `next()` without setting `req.principal`, but
 * `req.principal` is typed optional so TypeScript can't see that statically),
 * so it lives here once rather than four times. `GET /` is the one caller
 * that uses the `null` return directly (fails closed to an empty page,
 * matching `documents.ts`'s own `GET /` convention); every other route wants
 * `resolveWorkspaceOrThrow` below instead. */
async function resolveWorkspaceOrNull(req: Request, requestId: string): Promise<string | null> {
  const principal = req.principal;
  if (!principal) {
    throw serverError(requestId);
  }
  return resolvePrincipalWorkspaceId(principal);
}

/** `resolveWorkspaceOrNull`, but throws a `not_found` `ApiError` instead of
 * returning `null` — what every route except `GET /` wants: `GET /:id`,
 * `DELETE /:id`, and `POST /:id/rotate` all treat "no workspace resolves" as
 * equivalent to "nothing found", the same as a real id lookup miss. */
async function resolveWorkspaceOrThrow(req: Request, requestId: string): Promise<string> {
  const workspaceId = await resolveWorkspaceOrNull(req, requestId);
  if (!workspaceId) {
    throw notFoundError(requestId, 'No workspace is associated with this credential.');
  }
  return workspaceId;
}

// ─── POST /api/v1/webhooks ───────────────────────────────────────────────

webhooksRouter.post(
  '/',
  bearerAuth,
  rateLimitBuckets,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);

    const parseResult = CreateWebhookSubscriptionRequestSchema.safeParse(req.body);
    if (!parseResult.success) {
      throw validationFailedError(requestId, 'The request could not be validated.', {
        fieldErrors: parseResult.error.flatten().fieldErrors,
      });
    }

    const workspaceId = await resolveWorkspaceOrThrow(req, requestId);

    const appLookup = await pool.query<{ id: string }>(
      `SELECT id FROM oauth_apps WHERE id = $1 AND workspace_id = $2`,
      [parseResult.data.app_id, workspaceId]
    );
    if (!appLookup.rows[0]) {
      throw validationFailedError(requestId, 'app_id does not reference an app in your workspace.', {
        fieldErrors: { app_id: ['no such app in your workspace'] },
      });
    }

    const plaintextSecret = generateWebhookSecret();
    const ciphertext = encryptSecret(plaintextSecret);

    let result;
    try {
      result = await pool.query<WebhookSubscriptionRow>(
        `INSERT INTO webhook_subscriptions (app_id, event_type, target_url, signing_secret_ciphertext, active)
         VALUES ($1, $2, $3, $4, true)
         RETURNING id, app_id, event_type, target_url, active, created_at`,
        [parseResult.data.app_id, parseResult.data.event_type, parseResult.data.target_url, ciphertext]
      );
    } catch (error) {
      // 23505 = unique_violation — migration 047's
      // `idx_webhook_subscriptions_unique_active` partial unique index (app_id,
      // event_type, target_url) WHERE active. A caller-facing, actionable
      // error rather than a sanitized server_error: this is a validation
      // outcome (a duplicate active subscription), not an unexpected failure.
      if (isPgErrorWithCode(error, '23505')) {
        throw validationFailedError(
          requestId,
          'An active subscription for this app_id/event_type/target_url combination already exists.',
          { fieldErrors: { target_url: ['duplicate active subscription for this event_type and target_url'] } }
        );
      }
      throw error;
    }
    const row = result.rows[0];
    if (!row) {
      throw serverError(requestId);
    }

    // The only response, ever, that carries `secret`. Not stored anywhere
    // beyond this local variable and this one JSON body — AC: "secret
    // non-recoverable via API after creation."
    res.status(201).json({
      ...serializeSubscription(row),
      secret: plaintextSecret,
      warning: 'Save this secret now. It will not be shown again.',
    });
  })
);

// ─── GET /api/v1/webhooks ────────────────────────────────────────────────

webhooksRouter.get(
  '/',
  bearerAuth,
  rateLimitBuckets,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);

    const parseResult = ListWebhookSubscriptionsQuerySchema.safeParse(req.query);
    if (!parseResult.success) {
      throw validationFailedError(requestId, 'Invalid query parameters.', {
        fieldErrors: parseResult.error.flatten().fieldErrors,
      });
    }
    const { limit, cursor } = parseResult.data;

    let decodedCursor: KeysetCursor | null = null;
    if (cursor !== undefined) {
      decodedCursor = decodeCursor(cursor);
      if (!decodedCursor) {
        throw validationFailedError(requestId, 'Invalid cursor.', {
          fieldErrors: { cursor: ['cursor is not a valid opaque cursor'] },
        });
      }
    }

    const workspaceId = await resolveWorkspaceOrNull(req, requestId);
    if (!workspaceId) {
      // Same "fail closed to an empty page" convention as documents.ts.
      res.status(200).json({ data: [], next_cursor: null });
      return;
    }

    const values: unknown[] = [workspaceId];
    const whereClauses = ['a.workspace_id = $1'];

    if (decodedCursor) {
      values.push(decodedCursor.created_at, decodedCursor.id);
      whereClauses.push(`(ws.created_at, ws.id) < ($${values.length - 1}, $${values.length})`);
    }

    values.push(limit + 1);
    const limitParamIndex = values.length;

    const result = await pool.query<WebhookSubscriptionRow>(
      `SELECT ${SUBSCRIPTION_COLUMNS}
       FROM webhook_subscriptions ws
       JOIN oauth_apps a ON a.id = ws.app_id
       WHERE ${whereClauses.join(' AND ')}
       ORDER BY ws.created_at DESC, ws.id DESC
       LIMIT $${limitParamIndex}`,
      values
    );

    const rows = result.rows;
    const hasMore = rows.length > limit;
    const page = hasMore ? rows.slice(0, limit) : rows;
    const lastRow = page[page.length - 1];
    const nextCursor =
      hasMore && lastRow
        ? encodeCursor({ id: lastRow.id, created_at: lastRow.created_at.toISOString() })
        : null;

    res.status(200).json({
      data: page.map(serializeSubscription),
      next_cursor: nextCursor,
    });
  })
);

// ─── GET /api/v1/webhooks/deliveries ─────────────────────────────────────
//
// Registered BEFORE `GET /:id` — see file header for why route order
// matters here.

webhooksRouter.get(
  '/deliveries',
  bearerAuth,
  rateLimitBuckets,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);

    const parseResult = ListWebhookDeliveriesQuerySchema.safeParse(req.query);
    if (!parseResult.success) {
      throw validationFailedError(requestId, 'Invalid query parameters.', {
        fieldErrors: parseResult.error.flatten().fieldErrors,
      });
    }
    const { limit, cursor, subscription_id, status } = parseResult.data;

    let decodedCursor: KeysetCursor | null = null;
    if (cursor !== undefined) {
      decodedCursor = decodeCursor(cursor);
      if (!decodedCursor) {
        throw validationFailedError(requestId, 'Invalid cursor.', {
          fieldErrors: { cursor: ['cursor is not a valid opaque cursor'] },
        });
      }
    }

    const workspaceId = await resolveWorkspaceOrNull(req, requestId);
    if (!workspaceId) {
      // Same "fail closed to an empty page" convention as GET /.
      res.status(200).json({ data: [], next_cursor: null });
      return;
    }

    const values: unknown[] = [workspaceId];
    const whereClauses = ['a.workspace_id = $1'];

    if (subscription_id !== undefined) {
      values.push(subscription_id);
      whereClauses.push(`wd.subscription_id = $${values.length}`);
    }

    if (status !== undefined) {
      values.push(status);
      whereClauses.push(`wd.status = $${values.length}`);
    }

    if (decodedCursor) {
      values.push(decodedCursor.created_at, decodedCursor.id);
      whereClauses.push(`(wd.created_at, wd.id) < ($${values.length - 1}, $${values.length})`);
    }

    values.push(limit + 1);
    const limitParamIndex = values.length;

    const result = await pool.query<WebhookDeliveryRow>(
      `SELECT ${DELIVERY_COLUMNS}
       FROM webhook_deliveries wd
       JOIN webhook_subscriptions ws ON ws.id = wd.subscription_id
       JOIN oauth_apps a ON a.id = ws.app_id
       WHERE ${whereClauses.join(' AND ')}
       ORDER BY wd.created_at DESC, wd.id DESC
       LIMIT $${limitParamIndex}`,
      values
    );

    const rows = result.rows;
    const hasMore = rows.length > limit;
    const page = hasMore ? rows.slice(0, limit) : rows;
    const lastRow = page[page.length - 1];
    const nextCursor =
      hasMore && lastRow
        ? encodeCursor({ id: lastRow.id, created_at: lastRow.created_at.toISOString() })
        : null;

    res.status(200).json({
      data: page.map(serializeDelivery),
      next_cursor: nextCursor,
    });
  })
);

// ─── POST /api/v1/webhooks/deliveries/:id/replay ─────────────────────────
//
// PF-306 (Linear TRO-446). Registered here, alongside `GET /deliveries` and
// still BEFORE `GET /:id` — same Express route-ordering reasoning as
// `GET /deliveries` itself (see file header): `deliveries` is a literal path
// segment, so as long as anything under `/deliveries/*` is registered before
// the generic `/:id` pattern, the literal segment wins the match. (In this
// specific case segment COUNT alone would already disambiguate this route
// from `/:id` and `/:id/rotate` — 3 segments vs. 1 and 2 — but keeping every
// `/deliveries/*` route grouped together, before `/:id`, matches this file's
// existing convention and doesn't rely on that.)
//
// Looks up the ORIGINAL delivery row (workspace-scoped via the same
// oauth_apps join every other route in this file uses — a caller cannot
// replay another workspace's delivery), then re-runs it through the
// deliverer with the SAME idempotency_key the original delivery used (read
// off the row, never regenerated — the subscriber-dedupe contract PF-801's
// future e2e test verifies). Works for ANY original status, including
// 'dead' (DLQ) — this route never filters or branches on the original row's
// own status; that is the entire point of a DLQ-replay endpoint.
//
// Records a NEW delivery row rather than mutating the original (this
// ticket's own AC) — linked back via `replayed_from_id` (migration 049).
// Continues the SAME (subscription_id, event_id) attempt_number series
// rather than restarting at 1: migration 048's own unique index is keyed on
// (subscription_id, event_id, attempt_number), and idx_webhook_deliveries_
// event_id was added by that same migration specifically "in anticipation"
// of this route resolving every attempt of an event, replays included (see
// that migration's own header) — reusing event_id, not minting a fresh one,
// is what keeps that lookup meaningful for a replayed delivery.
//
// ACCEPTED CONSEQUENCE of continuing the series (CodeRabbit, this PR
// review): replaying a delivery that was already dead-lettered after
// exhausting `MAX_ATTEMPTS` (6) gets a replay `attempt_number` of 7+, which
// is already `>= MAX_ATTEMPTS`. If that replay attempt itself gets a
// retryable outcome (5xx/timeout), `attempt()`'s own pre-existing logic
// dead-letters it immediately, with NO further retry scheduled — same rule
// a 6th automatic attempt already follows, applied consistently to a
// replay. This is intentional, not a bug: a replay of an already-exhausted
// delivery that fails again is, correctly, still exhausted. An operator who
// wants another shot calls replay again.

interface ReplayLookupRow {
  id: string;
  subscription_id: string;
  event_id: string;
  event_type: string;
  payload: unknown;
  idempotency_key: string;
  target_url: string;
  signing_secret_ciphertext: string;
}

/** Bounded retry for the attempt_number race described below — not a
 * silent-forever loop. */
const REPLAY_ATTEMPT_NUMBER_MAX_RETRIES = 5;

webhooksRouter.post(
  '/deliveries/:id/replay',
  bearerAuth,
  rateLimitBuckets,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);
    const id = String(req.params.id);

    if (!UUID_RE.test(id)) {
      throw notFoundError(requestId);
    }

    const workspaceId = await resolveWorkspaceOrThrow(req, requestId);

    const lookup = await pool.query<ReplayLookupRow>(
      `SELECT wd.id, wd.subscription_id, wd.event_id, wd.event_type, wd.payload, wd.idempotency_key,
              ws.target_url, ws.signing_secret_ciphertext
       FROM webhook_deliveries wd
       JOIN webhook_subscriptions ws ON ws.id = wd.subscription_id
       JOIN oauth_apps a ON a.id = ws.app_id
       WHERE wd.id = $1 AND a.workspace_id = $2`,
      [id, workspaceId]
    );

    const original = lookup.rows[0];
    if (!original) {
      throw notFoundError(requestId);
    }

    // event_type is unconstrained TEXT (migration 048's own deliberate
    // "events as data" call) — validated against the registry rather than
    // blindly cast, same guard rehydrate() applies to a hand-edited or
    // pre-migration row (deliverer.ts).
    const eventType = original.event_type;
    if (!isKnownEventType(eventType)) {
      throw serverError(requestId);
    }

    // Re-serialized from the persisted jsonb, not necessarily byte-identical
    // to whatever the original attempt actually sent (Postgres jsonb does
    // not preserve key order/whitespace) — harmless, matching rehydrate()'s
    // own identical comment: this replay signs and sends this exact string,
    // fresh, and never needs to match a PAST attempt's exact bytes.
    const rawBody = JSON.stringify(original.payload);

    // Computed and inserted in ONE atomic INSERT ... SELECT — not a separate
    // read-then-write. `COALESCE(MAX(attempt_number), 0) + 1` is evaluated by
    // the database at INSERT time, not read back into this handler and
    // re-sent, so nothing here can go stale between a read and a write.
    // A genuine concurrent race (two replay calls for the SAME delivery
    // landing at once) can still both compute the same next number under
    // READ COMMITTED — resolved by retrying on the unique-index violation
    // (23505) rather than assumed away (lessons.md rule 18: "push the
    // predicate into the query, and state the concurrency argument" — the
    // predicate IS pushed into the query; the bounded retry is the
    // remaining, disclosed piece for the rare case two computations race).
    let insertedRow: { id: string; attempt_number: number } | undefined;
    for (let attempt = 0; attempt < REPLAY_ATTEMPT_NUMBER_MAX_RETRIES; attempt++) {
      try {
        const inserted = await pool.query<{ id: string; attempt_number: number }>(
          `INSERT INTO webhook_deliveries
             (subscription_id, event_id, event_type, payload, idempotency_key, attempt_number, status, replayed_from_id)
           SELECT $1, $2, $3, $4::jsonb, $5, COALESCE(MAX(attempt_number), 0) + 1, 'pending', $6
           FROM webhook_deliveries
           WHERE subscription_id = $1 AND event_id = $2
           RETURNING id, attempt_number`,
          [original.subscription_id, original.event_id, original.event_type, rawBody, original.idempotency_key, original.id]
        );
        insertedRow = inserted.rows[0];
        break;
      } catch (error) {
        if (isPgErrorWithCode(error, '23505') && attempt < REPLAY_ATTEMPT_NUMBER_MAX_RETRIES - 1) {
          continue;
        }
        throw error;
      }
    }

    if (!insertedRow) {
      throw serverError(requestId);
    }

    // Invoke delivery through the deliverer — never reimplement HTTP
    // delivery/signing here. A fresh instance is cheap (no I/O in the
    // constructor).
    //
    // KNOWN LIMITATION, CORRECTED (CodeRabbit, PR #229's review — an earlier
    // version of this comment claimed a singleton wouldn't change this;
    // that was wrong and has been retracted). `InMemoryWebhookDeliverer`
    // owns a PRIVATE in-memory `queue` array per instance (deliverer.ts).
    // If this replay's attempt is retryable (5xx/timeout) AND the original's
    // `attempt_number` was below `MAX_ATTEMPTS`, `attempt()` pushes a new
    // 'pending' retry-sibling row onto THIS throwaway instance's queue —
    // which is discarded the moment this request returns. The production
    // singleton (`api/src/index.ts`, `start()`'s polling `processDue()`)
    // never sees that sibling, because it lives on a different instance's
    // queue. The row is NOT lost (it is durably 'pending' in Postgres) but
    // it IS orphaned from live polling until the next process
    // restart/`rehydrate()` — a real, narrow gap, not a cosmetic one. It
    // does NOT affect the primary DLQ-replay use case (attempt_number
    // already >= MAX_ATTEMPTS never schedules a sibling — see the
    // 'PF-306: replay of a DLQ (dead) delivery' test below). The correct
    // fix is injecting the app's real running deliverer instance into this
    // route instead of constructing a throwaway one — a `createApp()`/
    // `index.ts` dependency-wiring change bigger than this ticket's own
    // scope, filed as TRO-603 rather than attempted here under this
    // sprint's deadline. See 'PF-306: a retryable replay leaves its retry
    // sibling un-polled until restart (TRO-603, documented not fixed)' below
    // for the regression test proving this is documented, known behavior.
    //
    // `attemptNow()` itself never throws for an HTTP-level outcome
    // (`performHttpAttempt()` catches every network/timeout failure into a
    // 'retryable' outcome, persisted normally) — but it CAN throw for a
    // process/deployment-level failure that isn't row-specific: a transient
    // DB error while persisting the outcome, or a non-deterministic
    // decrypt/sign failure (`attempt()`'s own doc comment — e.g. a GCM
    // auth-tag mismatch from a rotated `SECRET_ENCRYPTION_KEY_ENV`, which is
    // deliberately rethrown rather than dead-lettered, since it might not be
    // permanent). Letting that propagate as an opaque 500 would be
    // misleading: the NEW delivery row this request's whole job is to create
    // already exists and is a real, valid 'pending' record either way — the
    // 500 would suggest nothing happened when something did (CodeRabbit,
    // this PR review). Caught and logged; the response always reflects the
    // row's actual current state instead.
    const deliverer = new InMemoryWebhookDeliverer(pool);
    try {
      await deliverer.attemptNow({
        deliveryRowId: insertedRow.id,
        subscriptionId: original.subscription_id,
        eventId: original.event_id,
        eventType,
        targetUrl: original.target_url,
        signingSecretCiphertext: original.signing_secret_ciphertext,
        rawBody,
        idempotencyKey: original.idempotency_key,
        attemptNumber: insertedRow.attempt_number,
      });
    } catch (error) {
      console.error(
        `webhooks: replay attemptNow() failed to execute for new delivery row ${insertedRow.id} ` +
          `(replay of ${original.id}); the row remains 'pending', recoverable by a future rehydrate()`,
        error
      );
    }

    const finalResult = await pool.query<WebhookDeliveryRow>(
      `SELECT ${DELIVERY_COLUMNS} FROM webhook_deliveries wd WHERE wd.id = $1`,
      [insertedRow.id]
    );
    const finalRow = finalResult.rows[0];
    if (!finalRow) {
      throw serverError(requestId);
    }

    // 201 means the NEW delivery row was created and an attempt ran to
    // completion (or, per the catch above, at least was durably recorded as
    // 'pending' if the attempt itself failed to execute) — it does NOT mean
    // the subscriber accepted the delivery. `finalRow.status` is the
    // authoritative outcome: 'success', 'failed' (a retry sibling was
    // scheduled), 'dead' (permanent failure, or a replay whose continued
    // attempt_number already met MAX_ATTEMPTS — see this file's header for
    // that exhaustion case), or 'pending' (execution itself did not complete;
    // see the catch above).
    res.status(201).json(serializeDelivery(finalRow));
  })
);

// ─── GET /api/v1/webhooks/:id ────────────────────────────────────────────

webhooksRouter.get(
  '/:id',
  bearerAuth,
  rateLimitBuckets,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);
    const id = String(req.params.id);

    if (!UUID_RE.test(id)) {
      throw notFoundError(requestId);
    }

    const workspaceId = await resolveWorkspaceOrThrow(req, requestId);

    const result = await pool.query<WebhookSubscriptionRow>(
      `SELECT ${SUBSCRIPTION_COLUMNS}
       FROM webhook_subscriptions ws
       JOIN oauth_apps a ON a.id = ws.app_id
       WHERE ws.id = $1 AND a.workspace_id = $2`,
      [id, workspaceId]
    );

    const row = result.rows[0];
    if (!row) {
      throw notFoundError(requestId);
    }

    res.status(200).json(serializeSubscription(row));
  })
);

// ─── DELETE /api/v1/webhooks/:id ─────────────────────────────────────────

webhooksRouter.delete(
  '/:id',
  bearerAuth,
  rateLimitBuckets,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);
    const id = String(req.params.id);

    if (!UUID_RE.test(id)) {
      throw notFoundError(requestId);
    }

    const workspaceId = await resolveWorkspaceOrThrow(req, requestId);

    // Deactivates rather than deletes — see file header. No `active = true`
    // filter in the WHERE clause: a repeat call against an already-inactive
    // subscription still matches and still returns 204 (idempotent DELETE),
    // it just has nothing left to change.
    const result = await pool.query<{ id: string }>(
      `UPDATE webhook_subscriptions ws
       SET active = false
       FROM oauth_apps a
       WHERE ws.id = $1 AND ws.app_id = a.id AND a.workspace_id = $2
       RETURNING ws.id`,
      [id, workspaceId]
    );

    if (!result.rows[0]) {
      throw notFoundError(requestId);
    }

    res.status(204).send();
  })
);

// ─── POST /api/v1/webhooks/:id/rotate ────────────────────────────────────

webhooksRouter.post(
  '/:id/rotate',
  bearerAuth,
  rateLimitBuckets,
  requireScope('webhooks:manage'),
  asyncHandler(async (req, res) => {
    const requestId = requestIdOf(req);
    const id = String(req.params.id);

    if (!UUID_RE.test(id)) {
      throw notFoundError(requestId);
    }

    const workspaceId = await resolveWorkspaceOrThrow(req, requestId);

    const plaintextSecret = generateWebhookSecret();
    const ciphertext = encryptSecret(plaintextSecret);

    // Single-column UPDATE, no grace period — see file header (PF-102
    // `rotateOAuthAppSecret` precedent). The old ciphertext is gone the
    // instant this commits; nothing keeps it around for a fallback verify.
    const result = await pool.query<WebhookSubscriptionRow>(
      `UPDATE webhook_subscriptions ws
       SET signing_secret_ciphertext = $1
       FROM oauth_apps a
       WHERE ws.id = $2 AND ws.app_id = a.id AND a.workspace_id = $3
       RETURNING ws.id, ws.app_id, ws.event_type, ws.target_url, ws.active, ws.created_at`,
      [ciphertext, id, workspaceId]
    );

    const row = result.rows[0];
    if (!row) {
      throw notFoundError(requestId);
    }

    res.status(200).json({
      ...serializeSubscription(row),
      secret: plaintextSecret,
      warning: 'Save this secret now. It will not be shown again.',
    });
  })
);
