#!/usr/bin/env node
/**
 * cost-report.mjs — the "AI cost analysis" submission deliverable
 * (projectbrief.md: "Dev spend + reflection on AI tool effectiveness").
 *
 *   node scripts/factory/cost-report.mjs > audit/factory/COST_ANALYSIS.md
 *
 * Reads Claude Code's own session transcripts, which already record per-message
 * token usage — so this is retrospective and needed no instrumentation.
 *
 * PROVENANCE, and the report says this too: these are LIST-RATE estimates over
 * OBSERVED token counts. They are not billed spend. On a subscription plan the
 * marginal cost of these tokens is zero and the figure represents API-equivalent
 * value. Reporting an estimate as an invoice would be exactly the unmarked-
 * inference failure .claude/CLAUDE.md was written to prevent.
 */

import { cost } from './lib/state.mjs'

const c = cost()
if (!c.available) {
  console.error('No Claude Code transcripts found for this project.')
  process.exit(1)
}

const n = (x) => Number(x || 0).toLocaleString('en-US')
const pct = (x) => (x * 100).toFixed(1)
const total = c.totals.in + c.totals.out + c.totals.cw + c.totals.cr
const RATE = { in: 5, out: 25, cw: 6.25, cr: 0.5 }   // $/Mtok, Opus 5 list
const line = (k, tokens, rate) => `| ${k} | ${n(tokens)} | ${pct(tokens / total)}% | $${rate}/Mtok | $${((tokens / 1e6) * rate).toFixed(2)} |`

// What the same volume would cost with no cache: every cache read becomes a
// full-price input token, and cache writes lose their premium.
const uncached = ((c.totals.cr + c.totals.cw + c.totals.in) / 1e6) * RATE.in + (c.totals.out / 1e6) * RATE.out

process.stdout.write(`# AI Cost Analysis — ShipShape sprint

*Generated by \`scripts/factory/cost-report.mjs\` from Claude Code session transcripts.*

## What this number is, and is not

**These are list-rate estimates over observed token counts — not billed spend.**
Claude Code records per-message token usage in its session transcripts; this report
prices that usage at published Opus 5 API rates. If the work ran on a subscription
plan, the marginal cost of these tokens was **zero**, and the figure below is better
read as *API-equivalent value delivered* than as money spent.

Stating it either way without saying which would be an unmarked inference — the
failure mode this repository's \`CLAUDE.md\` exists to prevent.

## Totals

- **Sessions:** ${c.sessions}
- **Assistant messages with recorded usage:** ${n(c.messages)}
- **Total tokens:** ${n(total)}
- **Estimated value at list rates:** **$${c.usd.toFixed(2)}**

| Token class | Tokens | Share | Rate | Est. cost |
|---|---:|---:|---:|---:|
${line('Output', c.totals.out, RATE.out)}
${line('Cache write', c.totals.cw, RATE.cw)}
${line('Cache read', c.totals.cr, RATE.cr)}
${line('Raw input', c.totals.in, RATE.in)}

## The finding: this workflow's economics are prompt-cache economics

**${pct(c.cacheReadShare)}% of all token volume is cache reads**, billed at one tenth the
input rate. Raw uncached input is ${n(c.totals.in)} tokens — ${pct(c.totals.in / total)}% of volume.

Priced without caching — every cache read charged as a fresh input token — the same
work would cost roughly **$${uncached.toFixed(2)}**, about **${(uncached / c.usd).toFixed(1)}×** the actual estimate.

That ratio is the single most useful number here. It says the dominant cost driver in
agentic coding is not how much the model writes, but how much context it must re-read
per turn — and that the cache is doing nearly all the work of making it affordable.
Two practical consequences:

1. **Long sessions are cheap; fragmented ones are not.** Cache reads only stay cheap
   while the prefix is stable. Restarting context repeatedly converts 0.5×-rate reads
   into 5×-rate inputs — a 10× swing on the largest line item.
2. **Output is the real marginal cost.** At ${n(c.totals.out)} tokens it is
   ${pct(c.totals.out / total)}% of volume but $${((c.totals.out / 1e6) * RATE.out).toFixed(2)} of the estimate.
   Verbosity costs more than reading.

## Effectiveness for codebase comprehension

The audit measured 68 findings across 8 categories against a codebase nobody on the
team had seen before. Concrete things the tooling found that a manual read plausibly
would not have:

- **DB-1** — \`pnpm db:migrate\` exits 0 while abandoning 32 of 42 migrations. Silent
  success is invisible to inspection; it surfaced by running the thing and checking.
- **TEST-2** — 68 e2e tests pass without executing an assertion, including the only
  stored-XSS and audit-log-authz checks. A green suite hid it.
- **TS-1** — \`web/tsconfig.json\` does not extend the root config, hiding 102 latent
  type errors from the frontend.

And the counter-example worth recording: **A11Y-1** was first reported as "announced
incorrectly by screen readers", reasoned from an axe rule. A human running VoiceOver
found the titles are **not announced at all** — a worse defect. Automated comprehension
found the anomaly; it took a person to characterize it correctly.

*Rates: Opus 5 list — input $${RATE.in}, output $${RATE.out}, cache write $${RATE.cw}, cache read $${RATE.cr} per Mtok.*
`)
