/**
 * PF-202 (Linear TRO-402) — the generated `/api/v1` OpenAPI 3.1 document
 * itself: every registered route is present, and the document validates
 * against the real, official OpenAPI 3.1 JSON Schema.
 *
 * No `createApp()`/supertest here — `generateV1OpenAPIDocument()` is called
 * directly, so this suite needs no database and runs regardless of whether
 * the route is correctly mounted (that's `__tests__/endpoint.test.ts`'s
 * job).
 *
 * ## Why `@seriousme/openapi-schema-validator` instead of hand-rolled `ajv`
 *
 * Observed directly, before writing this test (this ticket, 2026-08-13):
 * compiling the real `spec.openapis.org/oas/3.1/schema` (draft 2020-12,
 * fetched via `@readme/openapi-schemas`) with `ajv/dist/2020` and validating
 * a genuine document generated by this same registry FAILED with
 * `unevaluatedProperties` errors at every inline Schema Object (e.g. the
 * `Document` component itself) — even though the document is a normal,
 * valid OpenAPI 3.1 document. Cross-checked against the OFFICIAL petstore
 * v3.1 fixture that `@seriousme/openapi-schema-validator` ships in its own
 * test suite: the identical hand-rolled `ajv.compile(schema)` setup rejects
 * that known-good fixture too. This is a documented `ajv` 8.x limitation in
 * how `$dynamicRef`/`$dynamicAnchor` interact with `unevaluatedProperties` —
 * `@seriousme/openapi-schema-validator` carries its own regression test for
 * exactly this (`test/test-ajv-dynamic-ref-bug.js` in that package) and
 * works around it internally, while its `Validator` class still uses
 * `ajv/dist/2020` (`Ajv2020`, draft 2020-12) against the same official
 * `spec.openapis.org` schema underneath. That satisfies the ticket's "ajv,
 * draft 2020-12" requirement without a looser or hand-waved check — it is a
 * different path to the same real validator, not a substitute for one.
 *
 * Also verified (not merely assumed) that this is a real, non-vacuous check:
 * the official petstore v3.1 fixture validates `true` through this same
 * library; a document missing required top-level fields validates `false`
 * (see "negative control" below, and PF-202's final report for the fixture
 * cross-check).
 */

import { describe, it, expect } from 'vitest';
import { Validator } from '@seriousme/openapi-schema-validator';
// Import from `../index.js`, NOT `../registry.js` directly — `registry.ts`
// only builds the (empty, at that point) registry and the generator
// function; `index.ts` is what imports `./schemas/index.js` for its
// registration side effects before `generateV1OpenAPIDocument` is ever
// called (see registry.ts's own header comment). Importing the bare
// `registry.js` produced a document with an EMPTY `paths` object the first
// time this test was written and run — caught by running it, not assumed.
import { generateV1OpenAPIDocument } from '../index.js';

describe('PF-202: generateV1OpenAPIDocument()', () => {
  const document = generateV1OpenAPIDocument();

  it('is an OpenAPI 3.1 document', () => {
    expect(document.openapi).toMatch(/^3\.1\.\d+$/);
  });

  it('registers every route on /api/v1 as of PF-305/PF-205/PF-501: health, openapi.json, documents (+4 sub-resources), issues, sprints (+{id}), me, webhooks (+deliveries), audit, people, changes', () => {
    // Updated by PF-203 (Linear TRO-404): issues/sprints/me (PF-201)
    // predated this registry landing and were never retrofitted — this
    // ticket's route-fitness test (route-fitness.test.ts) exists precisely
    // to catch that class of drift, and closing the gap it found is part of
    // this ticket, not a separate one. The two assertions this replaces
    // (one asserting the old, incomplete path set; one asserting issues/
    // sprints/me were deliberately absent) are corrections of now-stale
    // facts, not a weakened check — every path below is still individually
    // asserted present.
    //
    // Updated again by PF-302 (Linear TRO-431): /webhooks, /webhooks/{id},
    // /webhooks/{id}/rotate registered (`platform/openapi/schemas/webhooks.ts`)
    // — another legitimate addition to this hand-maintained list, same class
    // as the PF-203 update above, not a weakened check. Updated again by
    // PF-501 (Linear TRO-432): /audit registered
    // (`platform/openapi/schemas/audit.ts`).
    //
    // Updated again by PF-305 (Linear TRO-442): /webhooks/deliveries
    // registered (same file) — same class of legitimate addition, not a
    // weakened check; route-fitness.test.ts independently confirms this
    // route also carries a declared scope and the {data, next_cursor}
    // pagination envelope, which this file does not re-check.
    //
    // Updated again by PF-205 (Linear TRO-414): /people, /changes, the four
    // /documents/{id}/{associations,reverse-associations,backlinks,comments}
    // sub-resources, and /sprints/{id} — the agent's remaining reads. Same
    // class of legitimate addition, not a weakened check.
    const paths = document.paths ?? {};
    expect(Object.keys(paths).sort()).toEqual(
      [
        '/audit',
        '/changes',
        '/documents',
        '/documents/{id}',
        '/documents/{id}/associations',
        '/documents/{id}/backlinks',
        '/documents/{id}/comments',
        '/documents/{id}/reverse-associations',
        '/health',
        '/issues',
        '/me',
        '/openapi.json',
        '/people',
        '/sprints',
        '/sprints/{id}',
        '/webhooks',
        '/webhooks/deliveries',
        '/webhooks/{id}',
        '/webhooks/{id}/rotate',
      ].sort()
    );

    expect(paths['/health']?.get).toBeDefined();
    expect(paths['/openapi.json']?.get).toBeDefined();
    expect(paths['/documents']?.get).toBeDefined();
    expect(paths['/documents']?.post).toBeDefined();
    expect(paths['/documents/{id}']?.get).toBeDefined();
    expect(paths['/documents/{id}/associations']?.get).toBeDefined();
    expect(paths['/documents/{id}/reverse-associations']?.get).toBeDefined();
    expect(paths['/documents/{id}/backlinks']?.get).toBeDefined();
    expect(paths['/documents/{id}/comments']?.get).toBeDefined();
    expect(paths['/issues']?.get).toBeDefined();
    expect(paths['/sprints']?.get).toBeDefined();
    expect(paths['/sprints/{id}']?.get).toBeDefined();
    expect(paths['/me']?.get).toBeDefined();
    expect(paths['/webhooks']?.get).toBeDefined();
    expect(paths['/webhooks']?.post).toBeDefined();
    expect(paths['/webhooks/deliveries']?.get).toBeDefined();
    expect(paths['/webhooks/{id}']?.get).toBeDefined();
    expect(paths['/webhooks/{id}']?.delete).toBeDefined();
    expect(paths['/webhooks/{id}/rotate']?.post).toBeDefined();
    expect(paths['/audit']?.get).toBeDefined();
    expect(paths['/people']?.get).toBeDefined();
    expect(paths['/changes']?.get).toBeDefined();
  });

  it('every authenticated /api/v1 operation requires bearerAuth; health and openapi.json require none', () => {
    const paths = document.paths ?? {};
    expect(paths['/documents']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/documents']?.post?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/documents/{id}']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/issues']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/sprints']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/webhooks']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/webhooks']?.post?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/webhooks/deliveries']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/webhooks/{id}']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/webhooks/{id}']?.delete?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/webhooks/{id}/rotate']?.post?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/audit']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/people']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/changes']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/sprints/{id}']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/documents/{id}/associations']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/documents/{id}/reverse-associations']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/documents/{id}/backlinks']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/documents/{id}/comments']?.get?.security).toEqual([{ bearerAuth: [] }]);
    // /me requires bearerAuth like every other authenticated route — it just
    // requires no specific SCOPE (resources/me.ts's design decision; OpenAPI
    // security requirements for an http-bearer scheme don't carry a scope
    // list the way an oauth2 scheme's would, so this looks identical to
    // /documents' security entry despite that difference).
    expect(paths['/me']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/health']?.get?.security).toEqual([]);
    expect(paths['/openapi.json']?.get?.security).toEqual([]);
  });

  it('validates against the real, official OpenAPI 3.1 JSON Schema (draft 2020-12)', async () => {
    // Validator#validate expects Record<string, unknown> | string. A JSON
    // round-trip both satisfies that boundary honestly (an explicit local
    // type, not a cast — review-pattern rule 21) and matches exactly what a
    // client receives over HTTP, since Express's res.json() also serializes
    // the document through JSON.
    const rawDocument: Record<string, unknown> = JSON.parse(JSON.stringify(document));

    const validator = new Validator();
    const result = await validator.validate(rawDocument);

    expect(result.errors).toBeUndefined();
    expect(result.valid).toBe(true);
  });

  it('negative control: the same validator rejects a document missing required top-level fields', async () => {
    const validator = new Validator();
    const result = await validator.validate({ openapi: '3.1.0' });
    expect(result.valid).toBe(false);
  });
});
