/**
 * PF-202 (Linear TRO-402) — the generated `/api/v1` OpenAPI 3.1 document
 * itself: every registered route is present, and the document validates
 * against the real, official OpenAPI 3.1 JSON Schema.
 *
 * No `createApp()`/supertest here — `generateV1OpenAPIDocument()` is called
 * directly, so this suite needs no database and runs regardless of whether
 * the route is correctly mounted (that's `__tests__/endpoint.test.ts`'s
 * job).
 *
 * ## Why `@seriousme/openapi-schema-validator` instead of hand-rolled `ajv`
 *
 * Observed directly, before writing this test (this ticket, 2026-08-13):
 * compiling the real `spec.openapis.org/oas/3.1/schema` (draft 2020-12,
 * fetched via `@readme/openapi-schemas`) with `ajv/dist/2020` and validating
 * a genuine document generated by this same registry FAILED with
 * `unevaluatedProperties` errors at every inline Schema Object (e.g. the
 * `Document` component itself) — even though the document is a normal,
 * valid OpenAPI 3.1 document. Cross-checked against the OFFICIAL petstore
 * v3.1 fixture that `@seriousme/openapi-schema-validator` ships in its own
 * test suite: the identical hand-rolled `ajv.compile(schema)` setup rejects
 * that known-good fixture too. This is a documented `ajv` 8.x limitation in
 * how `$dynamicRef`/`$dynamicAnchor` interact with `unevaluatedProperties` —
 * `@seriousme/openapi-schema-validator` carries its own regression test for
 * exactly this (`test/test-ajv-dynamic-ref-bug.js` in that package) and
 * works around it internally, while its `Validator` class still uses
 * `ajv/dist/2020` (`Ajv2020`, draft 2020-12) against the same official
 * `spec.openapis.org` schema underneath. That satisfies the ticket's "ajv,
 * draft 2020-12" requirement without a looser or hand-waved check — it is a
 * different path to the same real validator, not a substitute for one.
 *
 * Also verified (not merely assumed) that this is a real, non-vacuous check:
 * the official petstore v3.1 fixture validates `true` through this same
 * library; a document missing required top-level fields validates `false`
 * (see "negative control" below, and PF-202's final report for the fixture
 * cross-check).
 */

import { describe, it, expect } from 'vitest';
import { Validator } from '@seriousme/openapi-schema-validator';
// Import from `../index.js`, NOT `../registry.js` directly — `registry.ts`
// only builds the (empty, at that point) registry and the generator
// function; `index.ts` is what imports `./schemas/index.js` for its
// registration side effects before `generateV1OpenAPIDocument` is ever
// called (see registry.ts's own header comment). Importing the bare
// `registry.js` produced a document with an EMPTY `paths` object the first
// time this test was written and run — caught by running it, not assumed.
import { generateV1OpenAPIDocument } from '../index.js';

describe('PF-202: generateV1OpenAPIDocument()', () => {
  const document = generateV1OpenAPIDocument();

  it('is an OpenAPI 3.1 document', () => {
    expect(document.openapi).toMatch(/^3\.1\.\d+$/);
  });

  it('registers every route that exists on /api/v1 as of this ticket: health, openapi.json, and the three documents routes', () => {
    const paths = document.paths ?? {};
    expect(Object.keys(paths).sort()).toEqual(
      ['/documents', '/documents/{id}', '/health', '/openapi.json'].sort()
    );

    expect(paths['/health']?.get).toBeDefined();
    expect(paths['/openapi.json']?.get).toBeDefined();
    expect(paths['/documents']?.get).toBeDefined();
    expect(paths['/documents']?.post).toBeDefined();
    expect(paths['/documents/{id}']?.get).toBeDefined();
  });

  it('deliberately does NOT register PF-201 routes (issues/sprints/me) — that ticket had not merged to main as of this dispatch (see this ticket\'s CHANGES.md scope note)', () => {
    const paths = document.paths ?? {};
    expect(paths['/issues']).toBeUndefined();
    expect(paths['/sprints']).toBeUndefined();
    expect(paths['/me']).toBeUndefined();
  });

  it('every /api/v1/documents operation requires bearerAuth; health and openapi.json require none', () => {
    const paths = document.paths ?? {};
    expect(paths['/documents']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/documents']?.post?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/documents/{id}']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(paths['/health']?.get?.security).toEqual([]);
    expect(paths['/openapi.json']?.get?.security).toEqual([]);
  });

  it('validates against the real, official OpenAPI 3.1 JSON Schema (draft 2020-12)', async () => {
    // Validator#validate expects Record<string, unknown> | string. A JSON
    // round-trip both satisfies that boundary honestly (an explicit local
    // type, not a cast — review-pattern rule 21) and matches exactly what a
    // client receives over HTTP, since Express's res.json() also serializes
    // the document through JSON.
    const rawDocument: Record<string, unknown> = JSON.parse(JSON.stringify(document));

    const validator = new Validator();
    const result = await validator.validate(rawDocument);

    expect(result.errors).toBeUndefined();
    expect(result.valid).toBe(true);
  });

  it('negative control: the same validator rejects a document missing required top-level fields', async () => {
    const validator = new Validator();
    const result = await validator.validate({ openapi: '3.1.0' });
    expect(result.valid).toBe(false);
  });
});
