/**
 * Generate TypeScript types for USWDS icon names, and a narrowed, eager
 * import map for the icons actually referenced in the app (TRO-201 / BUN-5).
 *
 * Two outputs, from two different scans, both under
 * src/components/icons/uswds/:
 *
 *  1. types.ts — reads every SVG filename from
 *     @uswds/uswds/dist/img/usa-icons/ and generates the full `IconName`
 *     union (autocomplete + compile-time validation for ANY icon the sprite
 *     ships, whether or not it's used yet). Unchanged behavior from before
 *     TRO-201.
 *
 *  2. usedIcons.generated.ts — scans web/src (via scanUsedIcons.ts, shared
 *     with Icon.test.tsx so the two can never drift apart) for every icon
 *     name actually passed to `<Icon name="...">`, and writes a static,
 *     eager import map of just those icons. Icon.tsx renders from this map
 *     instead of a whole-directory `import.meta.glob`, so unreferenced icons
 *     never ship. Adding a new `<Icon name="...">` call requires re-running
 *     this generator — see CHANGES.md's TRO-201 entry for why that tradeoff
 *     was made and what happens if it's forgotten (Icon.tsx logs a
 *     console.warn and renders null; it does not silently break the build).
 *
 * Run: pnpm generate:icon-types
 */

import { readdirSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { scanUsedIconNames } from '../src/components/icons/uswds/scanUsedIcons';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const USWDS_ICONS_PATH = resolve(
  __dirname,
  '../node_modules/@uswds/uswds/dist/img/usa-icons',
);
const ICON_SYSTEM_DIR = resolve(__dirname, '../src/components/icons/uswds');
const TYPES_OUTPUT_PATH = resolve(ICON_SYSTEM_DIR, 'types.ts');
const USED_ICONS_OUTPUT_PATH = resolve(
  ICON_SYSTEM_DIR,
  'usedIcons.generated.ts',
);
const SRC_DIR = resolve(__dirname, '../src');
const ICON_TSX_PATH = resolve(ICON_SYSTEM_DIR, 'Icon.tsx');

// Matches the absolute, project-root-relative path style the old
// whole-directory `import.meta.glob` used in Icon.tsx, so vite-plugin-svgr's
// `?react` transform applies identically to these static imports.
const ICON_SVG_BASE = '/node_modules/@uswds/uswds/dist/img/usa-icons';

function generateTypesFile(iconNames: string[]): void {
  const typeUnion = iconNames.map((name) => `  | '${name}'`).join('\n');

  const content = `/**
 * USWDS Icon Names
 *
 * Auto-generated by scripts/generate-icon-types.ts
 * Do not edit manually - run: pnpm generate:icon-types
 *
 * Total icons: ${iconNames.length}
 */

export type IconName =
${typeUnion};

/**
 * Array of all available icon names for runtime validation
 */
export const ICON_NAMES: IconName[] = [
${iconNames.map((name) => `  '${name}',`).join('\n')}
] as const;

/**
 * Check if a string is a valid icon name
 */
export function isValidIconName(name: string): name is IconName {
  return ICON_NAMES.includes(name as IconName);
}
`;

  writeFileSync(TYPES_OUTPUT_PATH, content);
  console.log(`Generated ${TYPES_OUTPUT_PATH}`);
  console.log(`Total icons: ${iconNames.length}`);
}

function generateUsedIconsFile(usedNames: string[], totalCount: number): void {
  // Reserved words (e.g. `delete`) can't be JS identifiers — prefix every
  // import binding so any current or future icon name is safe to use as one.
  const importLines = usedNames
    .map((name) => `import Icon_${name} from '${ICON_SVG_BASE}/${name}.svg?react';`)
    .join('\n');
  const mapEntries = usedNames
    .map((name) => `  ${JSON.stringify(name)}: Icon_${name},`)
    .join('\n');

  const content = `/// <reference types="vite-plugin-svgr/client" />
/**
 * Static, eager import map for USWDS icons referenced via
 * \`<Icon name="...">\` in web/src.
 *
 * Auto-generated by scripts/generate-icon-types.ts
 * Do not edit manually - run: pnpm generate:icon-types
 *
 * This is a SUBSET of types.ts's IconName union: types.ts documents every
 * icon the USWDS sprite ships (so any icon name type-checks), this file
 * eagerly bundles only the ones the app actually renders (see CHANGES.md's
 * TRO-201 entry). Adding a new \`<Icon name="...">\` call in web/src requires
 * re-running \`pnpm generate:icon-types\` — until then the new icon type-checks
 * but Icon.tsx renders null for it at runtime (with a console.warn).
 *
 * Icons referenced: ${usedNames.length} of ${totalCount} available
 */
import type { ComponentType, SVGProps } from 'react';
${importLines}

type SvgComponent = ComponentType<SVGProps<SVGSVGElement>>;

export const USED_ICON_NAMES = [
${usedNames.map((name) => `  '${name}',`).join('\n')}
] as const;

export const iconComponents: Partial<Record<string, SvgComponent>> = {
${mapEntries}
};
`;

  writeFileSync(USED_ICONS_OUTPUT_PATH, content);
  console.log(`Generated ${USED_ICONS_OUTPUT_PATH}`);
  console.log(`Icons referenced (eager): ${usedNames.length} of ${totalCount}`);
}

function generateIconTypes(): void {
  if (!existsSync(USWDS_ICONS_PATH)) {
    console.error(`Error: USWDS icons not found at ${USWDS_ICONS_PATH}`);
    console.error('Run: pnpm add @uswds/uswds');
    process.exit(1);
  }

  const files = readdirSync(USWDS_ICONS_PATH);
  const iconNames = files
    .filter((file) => file.endsWith('.svg'))
    .map((file) => file.replace('.svg', ''))
    .sort();

  if (iconNames.length === 0) {
    console.error('Error: No SVG icons found');
    process.exit(1);
  }

  generateTypesFile(iconNames);

  const validNames = new Set(iconNames);
  let usedNames: string[];
  try {
    usedNames = scanUsedIconNames(SRC_DIR, validNames, {
      excludeFiles: [TYPES_OUTPUT_PATH, ICON_TSX_PATH, USED_ICONS_OUTPUT_PATH],
    });
  } catch (err) {
    console.error(`Error: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
    return;
  }

  if (usedNames.length === 0) {
    console.error(
      'Error: found zero <Icon name="..."> usages in web/src — refusing to ' +
        'write an empty eager-load map (that would make every icon fail to ' +
        'render). If the app genuinely stopped using the Icon component, ' +
        'delete usedIcons.generated.ts and its import in Icon.tsx instead.',
    );
    process.exit(1);
  }

  generateUsedIconsFile(usedNames, iconNames.length);
}

// Only run when executed directly (`tsx scripts/generate-icon-types.ts`), not
// when imported — e.g. by a future test that wants scanUsedIconNames without
// the side effect of rewriting both output files.
if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  generateIconTypes();
}
