#!/usr/bin/env python3
"""
to_d2.py — factory model -> D2 source.

The HTML artifact is the thing you explore. The D2 file is the thing you commit:
a terse, diffable, renderer-independent statement of the same model, styled with
the same design-system tokens so a `d2` render and the artifact are siblings.

    python3 to_d2.py model.yaml > model.d2
    d2 --layout elk --theme 200 model.d2 model.svg
"""
from __future__ import annotations

import sys

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from analyze import analyze, load_model      # noqa: E402
from palette import build as build_tokens    # noqa: E402

KIND_SHAPE = {
    "intake": "oval", "transform": "rectangle", "gate": "diamond",
    "store": "cylinder", "release": "oval", "control": "hexagon",
    "external": "rectangle",
}
EDGE_STYLE = {
    "flow":      ("", 0, "ink"),
    "control":   ("", 3, "control"),
    "data":      ("", 0, "release"),
    "feedback":  ("", 5, "gate"),
    "recursion": ("", 2, "store"),
    "violation": ("", 0, "alert"),
    "gap":       ("", 6, "alert"),
}


def esc(s):
    return str(s).replace('"', "'").replace("\n", " ")


def to_d2(model, theme="dark"):
    tk = build_tokens()["themes"][theme]
    out = []
    meta = model.get("meta", {})
    out.append(f'# {esc(meta.get("title", "Factory"))}')
    if meta.get("source"):
        out.append(f'# source: {esc(meta["source"])}')
    out.append("# generated by system-graph / to_d2.py — edit the model, not this file")
    out.append("")
    out.append("direction: right")
    out.append("")

    # ---- design-system tokens as D2 vars + classes ------------------------
    out.append("vars: {")
    out.append("  d2-config: {")
    out.append(f'    theme-overrides: {{ B1: "{tk["ink"]}"; N1: "{tk["ink"]}" }}')
    out.append("  }")
    out.append("}")
    out.append("")
    out.append("classes: {")
    for kind in list(tk["kinds"]) + ["control", "external", "alert"]:
        c = tk["kinds"].get(kind) or tk[kind]
        out.append(f"  {kind}: {{")
        out.append(f"    shape: {KIND_SHAPE.get(kind, 'rectangle')}")
        out.append("    style: {")
        out.append(f'      fill: "{c["fill"]}"')
        out.append(f'      stroke: "{c["accent"]}"')
        out.append(f'      font-color: "{c["text"]}"')
        out.append("      stroke-width: 2")
        if kind == "external":
            out.append("      stroke-dash: 4")
        out.append("    }")
        out.append("  }")
    for ekind, (_d, dash, tone) in EDGE_STYLE.items():
        c = tk["ink_muted"] if tone == "ink" else (
            tk["kinds"].get(tone) or tk[tone])["accent"]
        out.append(f"  e-{ekind}: {{")
        out.append("    style: {")
        out.append(f'      stroke: "{c}"')
        out.append(f"      stroke-width: {3 if ekind in ('feedback', 'violation') else 2}")
        if dash:
            out.append(f"      stroke-dash: {dash}")
        out.append("    }")
        out.append("  }")
    out.append("}")
    out.append("")

    # ---- nodes, grouped by zone (containers = common region) -------------
    zones = {z["id"]: z for z in model.get("zones", [])}
    by_zone = {}
    for n in model["nodes"]:
        by_zone.setdefault(n.get("zone"), []).append(n)

    def emit_node(n, indent):
        p = " " * indent
        label = esc(n["label"])
        if n.get("subtitle"):
            label += f"\\n{esc(n['subtitle'])}"
        yield f'{p}{n["id"]}: "{label}" {{ class: {n.get("kind", "transform")} }}'

    for zid, ns in by_zone.items():
        if zid and zid in zones:
            z = zones[zid]
            out.append(f'{zid}: "{esc(z.get("label", zid))}" {{')
            out.append("  style: { stroke-dash: 3; border-radius: 12 }")
            for n in ns:
                out.extend(emit_node(n, 2))
            out.append("}")
        else:
            for n in ns:
                out.extend(emit_node(n, 0))
    out.append("")

    def ref(nid):
        z = next((n.get("zone") for n in model["nodes"] if n["id"] == nid), None)
        return f"{z}.{nid}" if z and z in zones else nid

    # ---- edges ------------------------------------------------------------
    for e in model["edges"]:
        kind = e.get("kind", "flow")
        bits = []
        if e.get("label"):
            bits.append(esc(e["label"]))
        if e.get("loop"):
            bits.append(f"[{e['loop']}{' ' + e['polarity'] if e.get('polarity') else ''}]")
        if kind == "gap":
            bits.append("MISSING?")
        label = f': "{" ".join(bits)}"' if bits else ":"
        out.append(f'{ref(e["from"])} -> {ref(e["to"])}{label} {{ class: e-{kind} }}')

    # ---- findings as a legend block --------------------------------------
    if model.get("findings"):
        out.append("")
        lines = "\\n".join(
            f"[{f['severity']}] {esc(f['title'])}" for f in model["findings"][:12])
        out.append(f'__findings: "OPEN QUESTIONS\\n\\n{lines}" {{')
        out.append("  class: alert")
        out.append("  shape: page")
        out.append("  near: bottom-left")
        out.append("}")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    print(to_d2(analyze(load_model(sys.argv[1]))), end="")
