/// <reference types="vite-plugin-svgr/client" />
/**
 * Static, eager import map for USWDS icons referenced via
 * `<Icon name="...">` in web/src.
 *
 * Auto-generated by scripts/generate-icon-types.ts
 * Do not edit manually - run: pnpm generate:icon-types
 *
 * This is a SUBSET of types.ts's IconName union: types.ts documents every
 * icon the USWDS sprite ships (so any icon name type-checks), this file
 * eagerly bundles only the ones the app actually renders (see CHANGES.md's
 * TRO-201 entry). Adding a new `<Icon name="...">` call in web/src requires
 * re-running `pnpm generate:icon-types` — until then the new icon type-checks
 * but Icon.tsx renders null for it at runtime (with a console.warn).
 *
 * Icons referenced: 4 of 245 available
 */
import type { ComponentType, SVGProps } from 'react';
import Icon_check from '/node_modules/@uswds/uswds/dist/img/usa-icons/check.svg?react';
import Icon_close from '/node_modules/@uswds/uswds/dist/img/usa-icons/close.svg?react';
import Icon_info from '/node_modules/@uswds/uswds/dist/img/usa-icons/info.svg?react';
import Icon_warning from '/node_modules/@uswds/uswds/dist/img/usa-icons/warning.svg?react';

type SvgComponent = ComponentType<SVGProps<SVGSVGElement>>;

export const USED_ICON_NAMES = [
  'check',
  'close',
  'info',
  'warning',
] as const;

export const iconComponents: Partial<Record<string, SvgComponent>> = {
  "check": Icon_check,
  "close": Icon_close,
  "info": Icon_info,
  "warning": Icon_warning,
};
