/**
 * Regenerate-or-check `docs/openapi.json` against the in-process `/api/v1`
 * OpenAPI 3.1 registry — PF-204 (Linear TRO-409), depends on PF-202 (Linear
 * TRO-402, `api/src/platform/openapi/`).
 *
 * `docs/openapi.json` is the PUBLIC v1 API spec (`generateV1OpenAPIDocument()`,
 * `OpenApiGeneratorV31` — PLUGFORGE.MD §4 PF-204, listed directly under
 * PF-202/PF-203 in Epic E2). It is a DIFFERENT document from the legacy
 * internal one: `api/openapi.json` / `api/openapi.yaml` (generated by
 * `src/scripts/generate-openapi.ts` -> `src/swagger.ts`'s
 * `generateOpenApiFile()`) document the internal `/api/*` surface with
 * `OpenApiGeneratorV3` (3.0.0). Do not confuse the two — this script only
 * ever touches `docs/openapi.json`.
 *
 * No app boot, no DATABASE_URL needed: `generateV1OpenAPIDocument()` only
 * walks the zod-to-openapi registry built by importing
 * `platform/openapi/schemas/*.ts`, the same thing
 * `platform/openapi/__tests__/document.test.ts` already relies on running
 * with no database (see that test's header comment) — verified again here by
 * running this script directly with no `DATABASE_URL` set.
 *
 * The pure functions below (`renderV1OpenApiSpec`, `diffAgainstCommitted`)
 * take no argument that depends on the module being run as the CLI entry
 * point, so `generate-v1-openapi.test.ts` can import and exercise them
 * directly — including a genuine drift case — without shelling out to a
 * subprocess or mutating the real committed `docs/openapi.json`. `main()`
 * only runs when this file is executed directly (the
 * `import.meta.url === entryUrl` guard at the bottom), never on import.
 *
 * Usage:
 *   tsx src/scripts/generate-v1-openapi.ts            # refresh: overwrite docs/openapi.json
 *   tsx src/scripts/generate-v1-openapi.ts --check     # CI drift check: regenerate in memory,
 *                                                        diff against the committed file, exit 1
 *                                                        on any difference. Never writes to
 *                                                        docs/openapi.json.
 *
 * One-command refresh procedure (documented again in CHANGES.md and
 * api/src/platform/openapi/README.md): `pnpm generate:openapi` from the repo
 * root, or `pnpm --filter @ship/api openapi:generate:v1` directly.
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { spawnSync } from 'child_process';
import { fileURLToPath } from 'url';
import { generateV1OpenAPIDocument } from '../platform/openapi/index.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// __dirname is <repo>/api/src/scripts at runtime (tsx runs the .ts source
// directly, it is never compiled to dist for this script) — three levels up
// reaches the repo root, where docs/ lives.
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
export const DEFAULT_COMMITTED_PATH = path.join(REPO_ROOT, 'docs', 'openapi.json');

/** Renders the current in-process /api/v1 registry as the exact string this
 * script writes to disk. Pure — no filesystem access. */
export function renderV1OpenApiSpec(): string {
  const document = generateV1OpenAPIDocument();
  // Trailing newline: matches how most editors/formatters leave a committed
  // JSON file, and keeps `git diff` on a future manual edit clean.
  return JSON.stringify(document, null, 2) + '\n';
}

export interface DriftResult {
  drift: boolean;
  /** True when committedPath does not exist at all — a distinct case from
   * "exists but differs", surfaced separately so the caller can give a more
   * specific message. */
  missing: boolean;
  rendered: string;
  committed: string | null;
}

/** Compares the freshly-rendered spec against whatever is on disk at
 * `committedPath`, without writing anything. Pure aside from the one read of
 * `committedPath` — takes the path as a parameter specifically so tests can
 * point it at a throwaway file instead of the real `docs/openapi.json`. */
export function diffAgainstCommitted(committedPath: string): DriftResult {
  const rendered = renderV1OpenApiSpec();

  if (!fs.existsSync(committedPath)) {
    return { drift: true, missing: true, rendered, committed: null };
  }

  const committed = fs.readFileSync(committedPath, 'utf-8');
  return { drift: committed !== rendered, missing: false, rendered, committed };
}

function refresh(committedPath: string): void {
  const rendered = renderV1OpenApiSpec();
  fs.writeFileSync(committedPath, rendered, 'utf-8');
  console.log(`v1 OpenAPI spec written to ${committedPath}`);
}

function check(committedPath: string): void {
  const result = diffAgainstCommitted(committedPath);

  if (result.missing) {
    console.error(`DRIFT: ${committedPath} does not exist.`);
    console.error(`Regenerate it with: pnpm generate:openapi`);
    process.exitCode = 1;
    return;
  }

  if (!result.drift) {
    console.log(`OK: ${committedPath} matches the in-process /api/v1 OpenAPI registry.`);
    return;
  }

  console.error(
    `DRIFT DETECTED: the committed ${committedPath} does not match what ` +
    `generateV1OpenAPIDocument() produces right now.\n`
  );

  // Best-effort readable diff for CI logs. `diff` is present on both graded
  // runners (ubuntu-latest for GitHub Actions, node:22-bookworm for GitLab
  // CI's .node_env) — if it is ever absent, fall back to a plain notice
  // rather than letting a missing binary mask the real drift failure below.
  const tmpPath = path.join(os.tmpdir(), `openapi-v1-drift-check-${process.pid}.json`);
  fs.writeFileSync(tmpPath, result.rendered, 'utf-8');
  const diffResult = spawnSync('diff', ['-u', committedPath, tmpPath], { encoding: 'utf-8' });
  if (diffResult.stdout) {
    console.error(diffResult.stdout);
  } else if (diffResult.error) {
    console.error(`(could not run 'diff' for a readable summary: ${diffResult.error.message})`);
  }

  console.error(`Regenerated spec left at ${tmpPath} for inspection.`);
  console.error(`Refresh the committed file with: pnpm generate:openapi`);
  process.exitCode = 1;
}

function main(): void {
  const checkMode = process.argv.includes('--check');
  if (checkMode) {
    check(DEFAULT_COMMITTED_PATH);
  } else {
    refresh(DEFAULT_COMMITTED_PATH);
  }
}

// Only run as a side effect of being executed directly (`tsx
// src/scripts/generate-v1-openapi.ts`), never on import — this is what lets
// generate-v1-openapi.test.ts import renderV1OpenApiSpec/diffAgainstCommitted
// without writing to the real docs/openapi.json.
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
