#!/bin/bash
# Dev server wrapper that finds available ports for multi-worktree development
#
# Strategy:
# 1. Ensure deps/shared are built, the database exists, is migrated (verified,
#    not just trusted) and seeded — idempotent, so this runs on EVERY start,
#    not only the first one (TRO-247 / RULE-6: a one-command start has to be
#    self-healing, not "correct once").
# 2. Scan actual port usage (not files) to find what's in use
# 3. Pick first available port pair (API: 3000+, Web: 5173+)
# 4. Write .ports file for reference (which worktree is where)
# 5. Start dev servers with those ports
#
# DATABASE_URL resolution (supports both a native Postgres install and a
# Docker one — see README "Cold start" for why both exist):
#   1. An explicit `DATABASE_URL` in the environment always wins.
#   2. Otherwise, an existing `api/.env.local` keeps its own value (so a plain
#      re-run never silently switches databases underneath a configured
#      worktree).
#   3. Otherwise, default exactly as before: postgresql://localhost/$DB_NAME,
#      where DB_NAME defaults to a name derived from this directory, or the
#      `DB_NAME` env var if set.
# Postgres itself does not have to be local: `ensureDatabase.ts` connects over
# plain TCP, which is all a Docker Postgres with its port published to the
# host (e.g. `docker-compose.local.yml`, :5433) needs — no `psql`/`createdb`
# dependency either way.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# --- 1. dependencies ---------------------------------------------------------
if [ ! -d "$ROOT_DIR/node_modules" ]; then
  echo "Installing dependencies..."
  (cd "$ROOT_DIR" && pnpm install)
fi
if [ ! -d "$ROOT_DIR/shared/dist" ]; then
  echo "Building shared package..."
  (cd "$ROOT_DIR" && pnpm build:shared)
fi

# --- 2. resolve DATABASE_URL --------------------------------------------------
EXISTING_DB_URL=""
if [ -f "$ROOT_DIR/api/.env.local" ]; then
  EXISTING_DB_URL="$(grep '^DATABASE_URL=' "$ROOT_DIR/api/.env.local" | head -1 | cut -d= -f2-)"
fi

if [ -n "${DATABASE_URL:-}" ]; then
  RESOLVED_DATABASE_URL="$DATABASE_URL"
elif [ -n "$EXISTING_DB_URL" ]; then
  RESOLVED_DATABASE_URL="$EXISTING_DB_URL"
else
  WORKTREE_NAME=$(basename "$ROOT_DIR")
  # Convert to valid postgres db name (lowercase, replace non-alphanumeric with _)
  DEFAULT_DB_NAME="ship_$(echo "$WORKTREE_NAME" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]' '_' | sed 's/_*$//')"
  RESOLVED_DATABASE_URL="postgresql://localhost/${DB_NAME:-$DEFAULT_DB_NAME}"
fi

# Ensure api/.env.local exists (only when missing — never overwrite a
# worktree's existing configuration).
if [ ! -f "$ROOT_DIR/api/.env.local" ]; then
  echo "Creating api/.env.local..."
  cat > "$ROOT_DIR/api/.env.local" << EOF
DATABASE_URL=$RESOLVED_DATABASE_URL
SESSION_SECRET=dev-secret-change-in-production
EOF
fi

# --- 3. database: exists, migrated (verified), seeded ------------------------
# All four steps are idempotent (ensureDatabase/migrate/seed no-op when
# already done; verifyMigrations is read-only) and run every invocation, so a
# re-run heals a partially-set-up environment instead of assuming yesterday's
# state is still true. `set -e` means any failure here — including
# `ensureDatabase.ts`'s actionable "Postgres unreachable" message, or
# `verifyMigrations.ts` catching a DB-1-shaped gap — stops the script instead
# of starting servers against a database that is not actually ready.
echo "Ensuring database exists..."
(cd "$ROOT_DIR/api" && DATABASE_URL="$RESOLVED_DATABASE_URL" npx tsx src/db/ensureDatabase.ts)

echo "Running migrations..."
(cd "$ROOT_DIR/api" && DATABASE_URL="$RESOLVED_DATABASE_URL" npx tsx src/db/migrate.ts)

echo "Verifying migrations..."
(cd "$ROOT_DIR/api" && DATABASE_URL="$RESOLVED_DATABASE_URL" npx tsx src/db/verifyMigrations.ts)

echo "Seeding database..."
(cd "$ROOT_DIR/api" && DATABASE_URL="$RESOLVED_DATABASE_URL" npx tsx src/db/seed.ts)

# Base ports
API_BASE=3000
WEB_BASE=5173

# Find an available port starting from base
find_available_port() {
  local base=$1
  local port=$base
  local max_attempts=20

  for ((i=0; i<max_attempts; i++)); do
    if ! lsof -i:$port >/dev/null 2>&1; then
      echo $port
      return 0
    fi
    ((port++))
  done

  echo "ERROR: Could not find available port after $max_attempts attempts (starting from $base)" >&2
  return 1
}

# Find available ports
echo "Finding available ports..."
API_PORT=$(find_available_port $API_BASE)
WEB_PORT=$(find_available_port $WEB_BASE)

echo "Using API port: $API_PORT"
echo "Using Web port: $WEB_PORT"

# Write .ports file for reference
cat > "$ROOT_DIR/.ports" << EOF
# Auto-generated by scripts/dev.sh
# This file shows which ports this worktree's dev server is using
# DO NOT EDIT - will be overwritten on next dev start
API=$API_PORT
WEB=$WEB_PORT
STARTED=$(date -Iseconds)
WORKTREE=$(basename "$ROOT_DIR")
EOF

echo "Wrote .ports file"

# Clean up .ports file on exit
cleanup() {
  if [ -f "$ROOT_DIR/.ports" ]; then
    rm -f "$ROOT_DIR/.ports"
    echo "Cleaned up .ports file"
  fi
}
trap cleanup EXIT INT TERM

# Export environment variables and start dev servers
export PORT=$API_PORT
export CORS_ORIGIN="http://localhost:$WEB_PORT"
export VITE_PORT=$WEB_PORT
export VITE_API_URL="http://localhost:$API_PORT"

echo "Starting dev servers..."
echo "  API: http://localhost:$API_PORT"
echo "  Web: http://localhost:$WEB_PORT"
echo ""

cd "$ROOT_DIR"
pnpm --parallel --recursive run dev
